### PR TITLE
[#73] Document the project's license (AGPL v3.0)

### PR DESCRIPTION
**Pull request by torfsen**
Adds a `LICENSE` file and a corresponding notice in `README.md` for the AGPL v3.0 license which is used for all CKAN extensions.

@amercader Please let me know if there is anything else that should be mentioned regarding license/copyright.

### CODE REVIEW

**Comment by torfsen** [comment]
Argh, the errors on Travis are unrelated to this PR.

**Comment by amercader** [comment]
Thanks for this @torfsen 

The errors are because of this: https://github.com/psycopg/psycopg2/issues/594

The workaround is to [upgrade psycopg2](https://github.com/okfn/rtei/commit/533be5fc36d87ab195e8081171409562aa1b920f) (tricky in CKAN's case) or maybe use an older travis image.

**Comment by neilmayhew** [comment]
It would also be helpful to enter a value in the `license` field in `setup.py`.

While you're at it, `url` and `keywords` are also empty.

**Comment by torfsen** [comment]
Thanks for the review, @amercader! I've fixed the Travis issue via workaround for ckanext-pages in 0081b250cca9670cdf22e07a95eb0808256e1d30 and [created a PR](https://github.com/ckan/ckan/pull/3996) to fix it in core CKAN.

As @neilmayhew has suggested I've also added the license information to `setup.py`.

**Pull request merged**
