### PR TITLE
install fanstatic templates (fixes #31)

### LINKED ISSUE #31: Error: 'module' object has no attribute 'pages/css/medium-editor.css'
I have installed this extension:

> git clone https://github.com/ckan/ckanext-pages.git ckanext-pages.git
> cd ckanext-pages.git
> pip install -r dev-requirements.txt
> python setup.py install

I have added to the config file of ckan this:

    ckan.plugins = ... pages ...
    ckanext.pages.allow_html = True
    ckanext.pages.editor = ckeditor

I have started the server but I get the error:

    File "/home/vagrant/ckan.git/local/lib/python2.7/site-packages/ckanext_pages-0.1-py2.7.egg/ckanext/pages/theme/templates_main/base.html", line 10, in block "links"
      {% resource 'pages/css/medium-editor.css' %}
    File "/home/vagrant/ckan.git/ckan/lib/jinja_extensions.py", line 315, in _call
      h.include_resource(args[0], **kwargs)
    File "/home/vagrant/ckan.git/ckan/lib/helpers.py", line 1358, in include_resource
      r = getattr(fanstatic_resources, resource)
    AttributeError: 'module' object has no attribute 'pages/css/medium-editor.css'

Do I have to install the editor manually?

### PR DESCRIPTION
**Pull request by grahame**
Fix setup.py so that the fanstatic CSS and JS files are installed.

### CODE REVIEW

**Comment by metaodi** [comment]
@grahame could you please rebase the master branch? The build fails because of an error I fixed today.

**Comment by grahame** [comment]
@metaodi done :-)

**Comment by metaodi** [comment]
@grahame Thanks. I was wondering if it might be better to put your change in the MANIFEST.in file instead of adding it to the `package_data`. WDYT?

There the line would be something like that:

```
recursive-include    ckanext/pages/fanstatic          *
```

**Comment by grahame** [comment]
@metaodi: no worries, done

**Comment by metaodi** [comment]
@grahame Perfect, thanks for this patch!

**Pull request merged**
