### PR TITLE
WIP: wysiwyg editor as alternative to markdown

### PR DESCRIPTION
**Pull request by deniszgonjanin**
Most open data publishers are civil servants. Civil servants don't have an interest in learning Markdown - they like their fancy CMS text editors. This gives them a simple and lightweight alternative.

This PR is useable, but so far only tested on ckan master

### CODE REVIEW

**Comment by joetsoi** [comment]
I like it.

I'm worried other people won't, it's not immediately obvious you're supposed to highlight text to change it, or that the # is how you create links. I don't think it would be clear to people who are used to word.

**Comment by joetsoi** [comment]
Ok, well as much as I like it, it does spectacularly fail the 'my mother is able to use it' test, because she was rather baffled.

We do have the ckeditor branch that could probably be merged that I think you bog standard user would be much more comfortable with. Does it meet your needs at all?  https://github.com/ckan/ckanext-pages/commits/ckeditor-blog

http://ckeditor.com/

**Comment by deniszgonjanin** [comment]
How is your mom's markdown? Because that's the default. I bet she's not using any markdown and is just entering plain text in those fields instead. And just like with markdown, this PR means she's able to continue entering just plain text. 

With CKEditor, things get more confusing. If you haven't used CKEditor before, it takes less time to learn how to use this toolbar than it does to learn how to work with CK and all of it's quirks.

Another benefit is that this can be used on forms instead of markdown. We are using it to enable rich text editing on Dataset forms. CKEditor is not an option there, it's too big and too heavy to have numerous instances of it on the same page. 

We're already using this on a couple of client sites, so that's another consideration for us why we can't go to CKEditor.

**Comment by amercader** [comment]
@deniszgonjanin for writing a significant piece of text the average user (let's leave @joetsoi mom out of this for now) is used to Microsoft Word. There is a text area and a bunch of toolbars on top, and CKEditor follows this pattern. IMO this is probably 10 times more boring but 100 times more usable for the average user:

mctckxw

We can definitely simplify buttons if we think they are not needed (spell checker...)

Also importantly, it is not obvious to me how can you add features like upload images, create tables, embed iframes, etc all of which CKEditor allows and which, I can guarantee, users ask for if they are supposed to edit static pages from the extension. This is a separate use case from the one you mention of editing descriptions in the dataset form, which of course should require a more light-weight feature set.

Having said all that, I'm definitely not against including the Medium editor, AFAICT it would be just a matter of adding a check [here](https://github.com/ckan/ckanext-pages/pull/17/files#diff-2102d60c55b8b8d0b1bf5a6d1ae14babL65) that takes a `ckanext.pages.editor` config option into account, and then you load one or the other (or none for Markdown fans). We can ship both and let admins choose, but IMO CKEditor should be the default.

As a bonus, we get the basic blog feature that the PR includes!

This seems like the best approach to me but happy to discuss further.

**Comment by deniszgonjanin** [comment]
I'm happy to maintain the medium editor feature if you guys choose to go that route.

Other option is to just go with CKEditor. I have no problems maintaining our own fork of pages, this PR is mostly here to contribute back to the project. If there is not much interest in it, don't merge it simply because somebody took the time to write it.

**Comment by amercader** [comment]
I think there is a real benefit with both of us (and any other org interested) maintaining the same fork of the extension, and having two editors (or the ability to add more) is a good feature anyway so happy to go down that route.

@joetsoi do you think we can get the blog branch merged, maybe write some basic tests and integrate @deniszgonjanin work? Does this sound like a plan?

**Comment by joetsoi** [comment]
sounds good to me

**Comment by deniszgonjanin** [comment]
Sounds good, thanks. Let me know if changes are needed to get this branch to play nice with the other one. I know you guys are pretty busy

**Comment by manuelpalacin** [comment]
Dear all,
I am testing the travis branch of ckan-pages. I've tested the blog to create some blog pages and it works fine (http://opengovernment.cloudapp.net/blog/blog1). But when I try to create a new page (pages not blogs), it allows me to edit using the ckeditor (I created some heading and characters in bold...) but then when I try to see the web page, it does not show any format (http://opengovernment.cloudapp.net/pages/legal9). It is strange cause in the pages list, it previews the image and the format (http://opengovernment.cloudapp.net/pages). I have checked the log but it does not appear any error. I am using CKAN 2.3 in Ubuntu 14.04 LTS. 

Do I have to put anything special in the production.ini file?

Many thanks!

**Pull request merged**
